EMACS ?= emacs

# lisp/*.el are concatenated (in load order) into one searchable, compiled file.
PARTS := package env core ui input completion lang org mail
SRC := $(wildcard lisp/*.el)
ELC := config.elc site-lisp/my-lazy-package.elc

.PHONY: all quickstart clean profile

all: $(ELC) quickstart

# Generated; init.el loads it (falling back to lisp/ when it is stale).
config.el: $(SRC) Makefile
	{ echo ';;; config.el --- GENERATED by make from lisp/*.el; do not edit -*- lexical-binding: t -*-'; \
	  for f in my-font my-util $(PARTS:%=init-%); do \
	    echo; echo ";;;; ==== lisp/$$f.el ===="; \
	    sed -e '1d' -e "/^(provide '/d" -e "/^(require 'init-core)/d" \
	        -e "/^(require 'my-\(font\|util\))/d" -e '/^;;;.* ends here/d' lisp/$$f.el; \
	  done; echo; echo ';;; config.el ends here'; } > $@

# Compile against the same load-path and use-package settings as init.el.
%.elc: %.el build.el
	$(EMACS) -Q --batch -l build.el -f batch-byte-compile $<

site-lisp/my-lazy-package.elc: site-lisp/my-lazy-package.el

quickstart:
	$(EMACS) -Q --batch --eval '(progn (setq package-quickstart t) (package-initialize) (package-quickstart-refresh))'

# Startup time (in a real frame; batch mode skips GUI-only setup).
profile:
	$(EMACS) --eval '(run-with-timer 3 nil (lambda () (message "init: %s" (emacs-init-time)) (kill-emacs)))' 2>&1 | grep -a "init:" || true

clean:
	$(RM) $(ELC) config.el package-quickstart.elc lisp/*.elc
